### PR TITLE
Fix SpecsFor to be compatible with NUnit 3.7.1

### PR DESCRIPTION
**Pull request by vpoorshab**
i had an issue with SpecsFor in my project when i updated the NUnit to 3.7.1 , the problem is all the test cases are failed due to an error in SpecsFor which was  **cannot find the TestFixture** so i only updated some attributes that have been replaced with new ones since Nunit 3.7.1
https://github.com/nunit/docs/wiki/SetUp-and-TearDown-Changes

### CODE REVIEW

**Comment by MattHoneycutt** [comment]
Thanks for the pull request!  NUnit 3.x support is something I have in the works, along with some other SpecsFor changes, so I'm going to leave this pull request here for now.

**Comment by peitschie** [comment]
Hi @MattHoneycutt ... just wondering if support for NUnit 3.x has progressed in the last 9 months? Any idea on when support may arrive?

**Comment by MattHoneycutt** [comment]
I've finally started making progress on this as of this week!  It's more than just NUnit 3 support, it's full .NET Standard compliance.  It's almost ready!

**Comment by MattHoneycutt** [comment]
This is available as part of the 6.0 pre-release, which is going to become the final release shortly.

**Pull request closed without merging**
