### PR TITLE
Enabling testing actions that call IsAjaxRequest

### PR DESCRIPTION
**Pull request by deap82**
Making it possible to test Controller Actions that calls IsAjaxRequest.

### CODE REVIEW

**Comment by deap82** [comment]
@MattHoneycutt Is this documentation also collaborative in any way?https://specsfor.readme.io/docs/specsforweb-helpers
If you accept my pull request it should be updated to include the IServerVariablesParamsProvider and IHeadersParamsProvider interfaces.

**Comment by deap82** [comment]
Had any chance to take a look at this?

**Comment by MattHoneycutt** [comment]
I apologize for not digging in to this yet.  I will do so today!

As for the documentation, it is indeed collaborative.  If you'd like to go
ahead and submit a pull request for the doc additions at readme.io, I would
be eternally grateful. :)

On Tue, Nov 17, 2015 at 3:14 AM deap82 <notifications@github.com> wrote:

> Had any chance to take a look at this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattHoneycutt/SpecsFor/pull/76#issuecomment-157315549>
> .
>
-- 
*Matt Honeycutt*
*Pluralsight Author & Senior Web Application Architect*
[image: Heroic Applications] <http://heroicapplications.com/>
pluralsight vids <http://www.pluralsight.com/author/matt-honeycutt> | blog
<http://trycatchfail.com/> | website <http://heroicapplications.com/> |
@matthoneycutt <http://twitter.com/matthoneycutt>

**Comment by MattHoneycutt** [comment]
Just FYI, this is now merged in!  Thanks for submitting this one, and I apologize again that it took me so long to get it processed.

**Comment by deap82** [comment]
Awesome. I saw that the nuget package is also updated. Is that automatic in some way?

**Comment by MattHoneycutt** [comment]
Unfortunately no, but I do have a PowerShell cmdlet that I created that
makes it stupid-easy to publish updates for any of my NuGet packages. :)

On Wed, Nov 18, 2015 at 12:56 AM deap82 <notifications@github.com> wrote:

> Awesome. I saw that the nuget package is also updated. Is that automatic
> in some way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattHoneycutt/SpecsFor/pull/76#issuecomment-157626673>
> .
>
-- 
*Matt Honeycutt*
*Pluralsight Author & Senior Web Application Architect*
[image: Heroic Applications] <http://heroicapplications.com/>
pluralsight vids <http://www.pluralsight.com/author/matt-honeycutt> | blog
<http://trycatchfail.com/> | website <http://heroicapplications.com/> |
@matthoneycutt <http://twitter.com/matthoneycutt>

**Pull request merged**
