### PR TITLE
fixing url should map to

### PR DESCRIPTION
**Pull request by neuhoffm**
Issue #57

### CODE REVIEW

**Comment by MattHoneycutt** [comment]
Thanks, I'll take a look at this pull request as soon as I can!

**Comment by neuhoffm** [comment]
How is this looking?

**Comment by MattHoneycutt** [comment]
Sorry for not getting this merged in already.  It's on my TODO list, but I
haven't quite gotten to it.  I should be able to catch up this week.

**Comment by MattHoneycutt** [comment]
I manually merged in the changes from this pull request.  They are part of the 4.5.0 release.  Thanks!

**Pull request closed without merging**
